## Basic Configuration
baseURL: http://stronglybranched.io/
languageCode: en-us
title: Strongly Branched
theme: hyde-hyde # https://github.com/htr3n/hyde-hyde.git

permalinks:
  posts: /:year/:month/:title/
# sections:
#   - posts

taxonomies:
  category: categories
  tag: tags

author: Tony Fortes Ramos
copyright: ©2019

# summarylength: 30
paginate: 5

menu:
  main:
    - identifier: home
      name: Home
      title: Home
      url: /
      weight: 1

    - identifier: archives
      name: Archives
      title: Archives
      url: /posts/
      weight: 2

    - identifier: categories
      name: Categories
      title: Categories
      url: /categories/
      weight: 3

    - identifier: tags
      name: Tags
      title: Tags
      url: /tags/
      weight: 4

    - identifier: about
      name: About
      title: About
      url: /about/
      weight: 5

params:
  author: Tony Fortes Ramos
  title: Title
  description: DevOps | Automation | Cloud | Infrastructure
  authorimage: ./images/sidebar.svg
  dateformat: 2006-01-02

  # sidebar, copyright & license
  copyright: Tony Fortes Ramos
  license: CC BY-SA 4.0
  licenseURL: https://creativecommons.org/licenses/by-sa/4.0
  showBuiltWith: true

  # https://highlightjs.org
  highlightjs: true
  highlightjsstyle: github

  # please choose either GraphComment or Disqus or Utterances
  #GraphCommentId: ...
  #UtterancesRepo: ... # https://utteranc.es/
  #UtterancesIssueTerm: ... # pathname, url, title, og:title
  #UtterancesTheme: ... # github-light or github-dark

  # Table of contents
  toc: hugo # none, hugo, tocbot

## Social Accounts
  social:
    github: draggeta
    linkedin: antoniofortesramos
    twitter: draggeta
    # email: amfortesramos@hotmail.com
    # instagram: <username>
    # xing: <username>
    # facebook: <username>
    # stackoverflow: <username>
    # telegram: <username>
    # gravatar: your-email@example.com
