## Basic Configuration
baseURL: https://stronglybranched.io/
defaultContentLanguage: en
title: Strongly Branched
theme: beautifulhugo # https://github.com/halogenica/beautifulhugo

enableGitInfo: true

author: Tony Fortes Ramos
copyright: ©2019

# summarylength: 30
# paginate: 5

permalinks:
  posts: /:year/:month/:title/

taxonomies:
  category: categories
  series: series
  tag: tags

menu:
  main:
  - identifier: home
    name: "Home"
    url: ""
    weight: 1

  - identifier: archives
    name: Archives
    title: Archives
    url: /posts/
    weight: 2

  - identifier: meta
    name: Meta
    weight: 3

  - parent: meta
    identifier: categories
    name: "Categories"
    url: categories
    weight: 1

  - parent: meta
    identifier: tags
    name: Tags
    url: tags
    weight: 2

  - identifier: about
    name: About
    title: About
    url: /about/
    weight: 5

privacy:
  disqus:
    disable: false
  googleAnalytics:
    disable: true
  instagram:
    disable: true
  twitter:
    disable: true
  vimeo:
    disable: true
  youtube:
    disable: true

# hugo gen chromastyles --style=monokai > static/css/syntax.css
pygmentsUseClasses: true
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true
# pygmentOptions: "linenos=inline"

# disqusShortname: stronglybranched
#googleAnalytics: "XXX"

params:
  # homeTitle: "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle: DevOps | Automation | Cloud | Infrastructure
  mainSections: [post, posts]
  logo: img/avatar-icon.svg # Expecting square dimensions
  favicon: img/favicon.ico
  copyright: "CC BY-SA 4.0"
  dateFormat: January 2, 2006

  commit: https://github.com/draggeta/blog/tree/
  rss: true

  comments: true
  readingTime: true
  wordCount: true

  showRelatedPosts: true
  # delayDisqus: true
  # useHLJS: true
  # socialShare: true
  # hideAuthor: true
  # gcse: 012345678901234567890:abcdefghijk # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

  staticman:
    api: api = "https://api.staticman.net/v3/entry/github/draggeta/blog/master/comments"
  #   recaptcha:
  #     sitekey: "6LeGeTgUAAAAAAqVrfTwox1kJQFdWl-mLzKasV0v"
  #     secret: "hsGjWtWHR4HK4pT7cUsWTArJdZDxxE2pkdg/ArwCguqYQrhuubjj3RS9C5qa8xu4cx/Y9EwHwAMEeXPCZbLR9eW1K9LshissvNcYFfC/b8KKb4deH4V1+oqJEk/JcoK6jp6Rr2nZV4rjDP9M7nunC3WR5UGwMIYb8kKhur9pAic="

  bigimg:
  - src: img/windmill.jpg
    desc: Windmill
    # https://www.goodfreephotos.com/netherlands/other/windmill-by-the-shoreline-in-the-netherlands.jpg.php

  - src: img/cladonia-rangiferina.jpg
    desc: Cladonia Rangiferina, cropped ©Gurfinkeld CC-BY-4.0
    # https://commons.wikimedia.org/wiki/File:Cladonia_rangiferina_-_%D0%9A%D0%BB%D0%B0%D0%B4%D0%BE%D0%BD%D0%B8%D1%8F_%D0%BE%D0%BB%D0%B5%D0%BD%D1%8C%D1%8F.jpg

  - src: img/cape-verde.jpg
    desc: Cape Verde ©NASA
    # https://earthobservatory.nasa.gov/images/19326/dust-over-cape-verde

  # - src: img/triangle.jpg
  #   desc: Triangle

  # - src: img/sphere.jpg
  #   desc: Sphere
  #   # position: see values of CSS background-position.
  #   position: center top

  # - src: img/hexagon.jpg
  #   desc: Hexagon

author:
  name: Tony Fortes Ramos
  github: draggeta
  twitter: draggeta
  linkedin: antoniofortesramos
  # email: youremail@domain.com
  # facebook: username
  # gitlab: username
  # bitbucket: username
  # reddit: username
  # xing: username
  # stackoverflow: users/XXXXXXX/username
  # snapchat: username
  # instagram: username
  # youtube: user/username # or channel/channelname
  # soundcloud: username
  # spotify: username
  # bandcamp: username
  # itchio: username
  # vk: username
  # paypal: username
  # telegram: username
  # 500px: username
  # codepen: username
  # mastodon: url
  # kaggle: username
  # website: yourwebsite.com
  # weibo: username
  # slack: username
