name: Adds submodule
author: draggeta
description: Adds the website submodule into the repo

runs:
  using: docker
  image: docker://jojomi/hugo:0.62.2
  entrypoint: /bin/sh
  args:
  - .github/scripts/build-deploy.sh
