name: Build GitHub Pages

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Build pages
      uses: klakegg/actions-hugo@1.0.0
      with:
        image: ext-alpine
        env: production

    - name: Commit and push
      run: |
        if ! git diff --no-ext-diff --quiet --exit-code; then
          cd public
          git config --local user.name "${GITHUB_ACTOR}"
          git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config user.name
          git config user.email
          git add .
          echo -n 'Files to Commit:' && ls -l | wc -l
          timestamp=$(date +%s%3N)
          git commit -a -m "Automated deployment to GitHub Pages on $timestamp"
          echo ${GHA_DEPLOY_KEY}
          echo "Done!"
        fi
    #       git remote set-url origin "$(git config --get remote.origin.url | sed 's#http.*com/#git@github.com:#g')"
    #       eval `ssh-agent -t 60 -s`
    #       echo ${GHA_DEPLOY_KEY} | ssh-add -
    #       mkdir -p ~/.ssh/
    #       ssh-keyscan github.com >> ~/.ssh/known_hosts
    #       git push
    #       ssh-agent -k
      env:
        GHA_DEPLOY_KEY: ${{ secrets.GHA_DEPLOY_KEY }}



    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GHA_DEPLOY_KEY }}
        branch: master
        directory: public
        repository: draggeta/draggeta.github.io

        # cd public
        # git config --global user.name ${GITHUB_ACTOR}
        # git config --global user.email ${GITHUB_ACTOR}@draggeta.nl
        # git add .
        # git commit -m "Update website"
        # git push origin HEAD:master
