name: Build GitHub Pages

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: hugo
      uses: klakegg/actions-hugo@1.0.0
      with:
        image: ext-alpine
        env: production
