name: Build GitHub Pages

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive

    - name: Build pages
      uses: klakegg/actions-hugo@1.0.0
      with:
        image: ext-alpine
        env: production

    - name: hugo-deploy-gh-org-pages
      uses: StevenACoffman/hugo-deploy-gh-org-pages@v1.0.4
      env:
        DEPLOY_KEY_PRIVATE: ${{ secrets.DEPLOY_KEY_PRIVATE }}
        EMAIL: ${GITHUB_ACTOR}@draggeta.nl
        HUGO_VERSION: 0.60.0
